dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - gcc-arm-linux-gnueabi

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.0.0/bazel_3.0.0-linux-x86_64.deb
  - wget https://github.com/bazelbuild/bazel/releases/download/3.0.0/bazel_3.0.0-linux-x86_64.deb.sha256
  - sha256sum -c bazel_3.0.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_3.0.0-linux-x86_64.deb

script:
  - bazel build //...
  - bazel test //...
  - sh release.sh
